# -*- coding: utf-8 -*-
"""Exoneración.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PwNkOu90DjDUgc8HBsyIYltUbpoKQJi0
"""

import random

# Clase base
class Usuario:
    def __init__(self, nombre, saldo):
        self.nombre = nombre
        self.saldo = saldo
        self.historial = []  # lista para guardar viajes

    def calcular_costo(self, km):
        return km * 0.50

    def recargar(self, monto):
        if monto > 0:
            self.saldo += monto
            print(f"Saldo recargado. Nuevo saldo: ${self.saldo:.2f}")
        else:
            print("Error: monto inválido")

    def realizar_viaje(self, km):
        if km <= 0:
            print("Error: kilometros invalidos")
            return

        costo = self.calcular_costo(km)

        if self.saldo >= costo:
            self.saldo -= costo
            self.historial.append(km)
            codigo = random.randint(100, 999)
            print(f"Viaje #{codigo} realizado! Costo: ${costo:.2f}. Saldo: ${self.saldo:.2f}")
        else:
            print("Error: saldo insuficiente")

    def ver_historial(self):
        print("=== HISTORIAL ===")
        if not self.historial:
            print("No hay viajes registrados")
        else:
            for i, km in enumerate(self.historial, 1):
                print(f"Viaje {i}: {km} km")

    def ver_perfil(self, detallado=True):
        if detallado:
            print("=== PERFIL (detallado) ===")
            print(f"Nombre: {self.nombre}")
            print(f"Tipo: Normal")
            print(f"Saldo: ${self.saldo:.2f}")
            print(f"Viajes: {len(self.historial)}")
        else:
            print(f"Nombre: {self.nombre} | Saldo: ${self.saldo:.2f}")

    def gasto_total(self):
        total = 0
        for km in self.historial:
            total += self.calcular_costo(km)
        return total


# Clase hija (herencia + polimorfismo)
class UsuarioPremium(Usuario):
    def calcular_costo(self, km):
        return km * 0.50 * 0.80  # 20% descuento

    def ver_perfil(self, detallado=True):
        if detallado:
            print("=== PERFIL (detallado) ===")
            print(f"Nombre: {self.nombre}")
            print(f"Tipo: Premium")
            print(f"Saldo: ${self.saldo:.2f}")
            print(f"Viajes: {len(self.historial)}")
        else:
            print(f"Nombre: {self.nombre} | Saldo: ${self.saldo:.2f}")


# MAIN con menú interactivo
def main():
    nombre = input("Nombre: ")
    tipo = int(input("Tipo (1=Normal, 2=Premium): "))
    saldo = float(input("Saldo inicial: "))

    if tipo == 2:
        usuario = UsuarioPremium(nombre, saldo)
    else:
        usuario = Usuario(nombre, saldo)

    while True:
        print("\n=== MENU ===")
        print("1. Recargar saldo")
        print("2. Realizar viaje")
        print("3. Ver historial")
        print("4. Ver perfil")
        print("5. Ver gasto total")
        print("6. Salir")

        opcion = input("Opcion: ")

        if opcion == "1":
            monto = float(input("Monto a recargar: "))
            usuario.recargar(monto)

        elif opcion == "2":
            km = float(input("Kilometros: "))
            usuario.realizar_viaje(km)

        elif opcion == "3":
            usuario.ver_historial()

        elif opcion == "4":
            modo = input("¿Detallado? (s/n): ").lower()
            usuario.ver_perfil(detallado=(modo == "s"))

        elif opcion == "5":
            total = usuario.gasto_total()
            print(f"Gasto total: ${total:.2f}")

        elif opcion == "6":
            print("Gracias por usar el servicio")
            break

        else:
            print("Opcion invalida")


# Ejecutar programa
main()